services:
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: expense_tracker_api_app

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - app
        container_name: expense_tracker_api_nginx

    db:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_DB: expense_tracker_api_db
            POSTGRES_USER: expense_user
            POSTGRES_PASSWORD: secret
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        container_name: expense_tracker_api_db
